### ISSUE TITLE
Walkman is not work

### ISSUE THREAD

**Issue by burrrkeye** [cmss13-devs/cmss13-pve#346]
### Testmerges

i forgor

### Round ID

i forgor

### Description of the bug

It won't play anything

### What's the difference with what should have happened?

it shouldve played music

### How do we reproduce this bug?

1.buy walkman
2.insert caset
3.yes
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment]
i already fixed this i just made you fill out a bug report as a teachable moment. it's not a bug though, walkmans are on the server host to provide files for
